app: 
  build:
    name: "@project.name@"
    artifact: "@project.artifactId@"
    version: "@project.version@"
    timestamp: "@project.build.timestamp@"



eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka.credentials.uri}/eureka/
      